site_name: Strojno učenje
site_url: https://www.strojnoucenje.si/
site_author: Sašo Karakatič
site_description: >-
  Pomoč pri uporabi strojnega učenja v Pythonu.

copyright: Vse pravice pridržane &copy; 2022 Sašo Karakatič, Iztok Fister ml.

nav:
  - Domov: "index.md"
  - Gradivo:
    - Povzetek gradiva: "pages/knjiga/00_knjiga.md"
    - Uvod: "pages/knjiga/01_uvod.md"
    - Vzpostavitev okolja: "pages/knjiga/02_okolje.md"
    - Strojno učenje: "pages/knjiga/03_strojno_ucenje.md"
    - Klasifikacija: "pages/knjiga/04_klasifikacija.md"
    - K najbližjih sosedov: "pages/knjiga/05_knn.md"
    - Kakovost klasifikacije: "pages/knjiga/06_kakovost_klasifikacije.md"
    - O gradivu: "pages/knjiga/09_o_gradivu.md"
  #- Sodelovanje: "pages/sodelovanje.md"
  - Avtorja: "pages/avtorja.md"
plugins:
  - search
theme:
  language: sl
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Preklopi na temno
      primary: indigo
      accent: teal
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Preklopi na svetlo
      primary: indigo
      accent: teal
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - instant
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:saso.karakatic@um.si
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sasokarakatic/
markdown_extensions:
  - tables
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
